/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ChatPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/view.ts
var import_obsidian3 = require("obsidian");

// src/common.ts
var import_obsidian = require("obsidian");
var PLUGIN_ID = "arenasys-ai-chat";
function setIcon(el, name) {
  var _a;
  el.empty();
  el.appendChild((_a = (0, import_obsidian.getIcon)(name)) != null ? _a : (0, import_obsidian.getIcon)("bug"));
}
function setLoader(el) {
  var loader = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 200" class="asys__loader"><circle fill="currentColor" stroke="currentColor" stroke-width="15" r="15" cx="40" cy="100"><animate attributeName="opacity" calcMode="spline" dur="2" values="1;0;1;" keySplines=".5 0 .5 1;.5 0 .5 1" repeatCount="indefinite" begin="-.4"></animate></circle><circle fill="currentColor" stroke="currentColor" stroke-width="15" r="15" cx="100" cy="100"><animate attributeName="opacity" calcMode="spline" dur="2" values="1;0;1;" keySplines=".5 0 .5 1;.5 0 .5 1" repeatCount="indefinite" begin="-.2"></animate></circle><circle fill="currentColor" stroke="currentColor" stroke-width="15" r="15" cx="160" cy="100"><animate attributeName="opacity" calcMode="spline" dur="2" values="1;0;1;" keySplines=".5 0 .5 1;.5 0 .5 1" repeatCount="indefinite" begin="0"></animate></circle></svg>';
  el.empty();
  el.insertAdjacentHTML("afterbegin", loader);
}
var HTTPStatus = {
  "0": "Unknown",
  "200": "OK",
  "201": "Created",
  "202": "Accepted",
  "203": "Non-Authoritative Information",
  "204": "No Content",
  "205": "Reset Content",
  "206": "Partial Content",
  "300": "Multiple Choices",
  "301": "Moved Permanently",
  "302": "Found",
  "303": "See Other",
  "304": "Not Modified",
  "305": "Use Proxy",
  "306": "Unused",
  "307": "Temporary Redirect",
  "400": "Bad Request",
  "401": "Unauthorized",
  "402": "Payment Required",
  "403": "Forbidden",
  "404": "Not Found",
  "405": "Method Not Allowed",
  "406": "Not Acceptable",
  "407": "Proxy Authentication Required",
  "408": "Request Timeout",
  "409": "Conflict",
  "410": "Gone",
  "411": "Length Required",
  "412": "Precondition Required",
  "413": "Request Entry Too Large",
  "414": "Request-URI Too Long",
  "415": "Unsupported Media Type",
  "416": "Requested Range Not Satisfiable",
  "417": "Expectation Failed",
  "418": "I'm a teapot",
  "429": "Too Many Requests",
  "500": "Internal Server Error",
  "501": "Not Implemented",
  "502": "Bad Gateway",
  "503": "Service Unavailable",
  "504": "Gateway Timeout",
  "505": "HTTP Version Not Supported"
};

// node_modules/eventsource-parser/dist/index.js
function createParser(onParse) {
  let isFirstChunk;
  let buffer;
  let startingPosition;
  let startingFieldLength;
  let eventId;
  let eventName;
  let data;
  reset();
  return {
    feed,
    reset
  };
  function reset() {
    isFirstChunk = true;
    buffer = "";
    startingPosition = 0;
    startingFieldLength = -1;
    eventId = void 0;
    eventName = void 0;
    data = "";
  }
  function feed(chunk) {
    buffer = buffer ? buffer + chunk : chunk;
    if (isFirstChunk && hasBom(buffer)) {
      buffer = buffer.slice(BOM.length);
    }
    isFirstChunk = false;
    const length = buffer.length;
    let position = 0;
    let discardTrailingNewline = false;
    while (position < length) {
      if (discardTrailingNewline) {
        if (buffer[position] === "\n") {
          ++position;
        }
        discardTrailingNewline = false;
      }
      let lineLength = -1;
      let fieldLength = startingFieldLength;
      let character;
      for (let index = startingPosition; lineLength < 0 && index < length; ++index) {
        character = buffer[index];
        if (character === ":" && fieldLength < 0) {
          fieldLength = index - position;
        } else if (character === "\r") {
          discardTrailingNewline = true;
          lineLength = index - position;
        } else if (character === "\n") {
          lineLength = index - position;
        }
      }
      if (lineLength < 0) {
        startingPosition = length - position;
        startingFieldLength = fieldLength;
        break;
      } else {
        startingPosition = 0;
        startingFieldLength = -1;
      }
      parseEventStreamLine(buffer, position, fieldLength, lineLength);
      position += lineLength + 1;
    }
    if (position === length) {
      buffer = "";
    } else if (position > 0) {
      buffer = buffer.slice(position);
    }
  }
  function parseEventStreamLine(lineBuffer, index, fieldLength, lineLength) {
    if (lineLength === 0) {
      if (data.length > 0) {
        onParse({
          type: "event",
          id: eventId,
          event: eventName || void 0,
          data: data.slice(0, -1)
          // remove trailing newline
        });
        data = "";
        eventId = void 0;
      }
      eventName = void 0;
      return;
    }
    const noValue = fieldLength < 0;
    const field = lineBuffer.slice(index, index + (noValue ? lineLength : fieldLength));
    let step = 0;
    if (noValue) {
      step = lineLength;
    } else if (lineBuffer[index + fieldLength + 1] === " ") {
      step = fieldLength + 2;
    } else {
      step = fieldLength + 1;
    }
    const position = index + step;
    const valueLength = lineLength - step;
    const value = lineBuffer.slice(position, position + valueLength).toString();
    if (field === "data") {
      data += value ? "".concat(value, "\n") : "\n";
    } else if (field === "event") {
      eventName = value;
    } else if (field === "id" && !value.includes("\0")) {
      eventId = value;
    } else if (field === "retry") {
      const retry = parseInt(value, 10);
      if (!Number.isNaN(retry)) {
        onParse({
          type: "reconnect-interval",
          value: retry
        });
      }
    }
  }
}
var BOM = [239, 187, 191];
function hasBom(buffer) {
  return BOM.every((charCode, index) => buffer.charCodeAt(index) === charCode);
}

// src/api.ts
var import_node_events = require("events");
var import_node_https = require("https");
var import_node_http = require("http");

// src/images.ts
var fs = __toESM(require("fs"));
var path = __toESM(require("path"));
var import_obsidian2 = require("obsidian");
var IMAGE_DRAG_TYPE = "application/x-asys-image-drag";
function deriveImageExtension(image, fallback = "png") {
  var _a;
  const map = {
    "image/png": "png",
    "image/jpeg": "jpg",
    "image/webp": "webp",
    "image/gif": "gif",
    "image/bmp": "bmp",
    "image/avif": "avif",
    "image/svg+xml": "svg"
  };
  return (_a = map[image.mime]) != null ? _a : fallback;
}
function downloadImageAsset(image) {
  const link = document.createElement("a");
  const timestamp = window.moment().format("YYYYMMDD_HHmmss");
  const ext = deriveImageExtension(image);
  const filename = `obsidian_${timestamp}.${ext}`;
  link.href = image.url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  link.remove();
}
async function saveImageToFolder(image, folder, filename) {
  try {
    const targetDir = path.isAbsolute(folder) ? folder : path.resolve(folder);
    await fs.promises.mkdir(targetDir, { recursive: true });
    const targetPath = path.join(targetDir, filename);
    await imageAssetToFS(image, targetPath);
    return true;
  } catch (err) {
    console.error("Failed to save image", err);
    return false;
  }
}
async function autoSaveImageAsset(image, folder) {
  const timestamp = window.moment().format("YYYYMMDD_HHmmss");
  const ext = deriveImageExtension(image);
  const suffix = Math.random().toString(36).slice(2, 6);
  const filename = `obsidian_${timestamp}_${suffix}.${ext}`;
  await saveImageToFolder(image, folder, filename);
}
var ImageList = class {
  constructor(container, options = {}) {
    this.container = container;
    this.options = options;
    this.images = [];
    this.dragIndex = null;
    this.dragPreviewEl = null;
    this.container.addEventListener("dragover", (event) => {
      if (!this.isOurDrag(event))
        return;
      if (this.dragIndex === null)
        return;
      const index = this.getDropTargetFromPosition(event.clientX);
      if (index === null)
        return;
      event.preventDefault();
      this.updateDropIndicator(index);
    });
    this.container.addEventListener("dragexit", (event) => {
      if (!this.isOurDrag(event))
        return;
      if (this.dragIndex === null)
        return;
      this.clearDropIndicators();
    });
    this.container.addEventListener("drop", (event) => {
      if (!this.isOurDrag(event))
        return;
      if (this.dragIndex === null)
        return;
      event.preventDefault();
      const index = this.getDropTargetFromPosition(event.clientX);
      if (index !== null) {
        this.moveImage(this.dragIndex, index);
      }
      this.resetDragState();
    });
  }
  updateOptions(options) {
    this.options = { ...this.options, ...options };
  }
  setImages(images, selectedIndex) {
    this.images = images;
    if (selectedIndex !== void 0) {
      this.options.selectedIndex = selectedIndex;
    }
    if (this.options.showSelection) {
      if (this.images.length === 0) {
        this.options.selectedIndex = void 0;
      } else if (this.options.selectedIndex === void 0) {
        this.options.selectedIndex = 0;
      } else {
        this.options.selectedIndex = Math.min(
          Math.max(this.options.selectedIndex, 0),
          this.images.length - 1
        );
      }
    }
    this.render();
  }
  setSelectedIndex(index, instant = false) {
    if (!this.options.showSelection)
      return;
    if (index < 0 || index >= this.images.length)
      return;
    this.options.selectedIndex = index;
    Array.from(this.container.children).forEach((child, childIndex) => {
      child.toggleClass(
        "asys__image-selected",
        childIndex === index
      );
    });
    this.centerSelected(instant);
  }
  centerSelected(instant = false) {
    var _a;
    if (!this.options.showSelection)
      return;
    const selected = this.container.children[(_a = this.options.selectedIndex) != null ? _a : -1];
    if (!selected)
      return;
    const container = this.container;
    const scrollTo = () => {
      const offset = selected.offsetLeft + selected.offsetWidth / 2 - container.clientWidth / 2;
      const maxScroll = Math.max(
        0,
        container.scrollWidth - container.clientWidth
      );
      const target = Math.max(0, Math.min(maxScroll, offset));
      container.scrollTo({
        left: target,
        behavior: instant ? "auto" : "smooth"
      });
    };
    if (instant) {
      scrollTo();
    } else {
      requestAnimationFrame(scrollTo);
    }
  }
  clearDropIndicators() {
    Array.from(this.container.children).forEach((child) => {
      child.removeClass("asys__image-drop-before");
      child.removeClass("asys__image-drop-after");
    });
  }
  resetDragState() {
    var _a;
    this.dragIndex = null;
    (_a = this.dragPreviewEl) == null ? void 0 : _a.remove();
    this.dragPreviewEl = null;
    Array.from(this.container.children).forEach((child) => {
      child.removeClass("asys__image-placeholder");
      child.removeClass("asys__image-drop-before");
      child.removeClass("asys__image-drop-after");
    });
  }
  updateDropIndicator(index) {
    this.clearDropIndicators();
    let dropAfter = false;
    if (index == this.container.children.length) {
      dropAfter = true;
      index = index - 1;
    }
    let wrapper = this.container.children[index];
    wrapper.addClass(
      dropAfter ? "asys__image-drop-after" : "asys__image-drop-before"
    );
  }
  getDropTargetFromPosition(clientX) {
    const wrappers = Array.from(this.container.children);
    if (wrappers.length === 0)
      return null;
    let index = null;
    for (let i = 0; i < wrappers.length; i++) {
      const rect = wrappers[i].getBoundingClientRect();
      const midpoint = rect.left + rect.width / 2;
      if (clientX < midpoint) {
        index = i;
        break;
      }
      if (i === wrappers.length - 1) {
        index = i + 1;
      }
    }
    return index;
  }
  moveImage(from, to) {
    var _a, _b;
    if (from < 0 || from >= this.images.length || to < 0 || to > this.images.length) {
      return;
    }
    const [image] = this.images.splice(from, 1);
    let target = to;
    if (from < to) {
      target -= 1;
    }
    this.images.splice(target, 0, image);
    (_b = (_a = this.options).onReorder) == null ? void 0 : _b.call(_a, this.images);
    this.render();
  }
  render() {
    this.container.empty();
    if (this.images.length === 0) {
      this.container.addClass("asys__hidden");
      this.container.style.display = "none";
      return;
    }
    this.container.removeClass("asys__hidden");
    this.container.style.display = "";
    const showDownload = this.options.showDownload === void 0 ? true : this.options.showDownload;
    this.images.forEach((image, index) => {
      const wrapper = this.container.createDiv({
        cls: "asys__image-wrapper"
      });
      if (this.options.showSelection && this.options.selectedIndex === index) {
        wrapper.addClass("asys__image-selected");
      }
      const img = wrapper.createEl("img", {
        attr: {
          src: image.url
        }
      });
      wrapper.addEventListener("click", () => {
        var _a, _b;
        (_b = (_a = this.options).onClick) == null ? void 0 : _b.call(_a, image, index);
        if (this.options.showSelection) {
          this.setSelectedIndex(index);
        }
      });
      if (showDownload) {
        const download = wrapper.createEl("button", {
          cls: "asys__image-download asys__image-action asys__icon clickable-icon"
        });
        setIcon(download, "download");
        download.ariaLabel = "Download image";
        download.addEventListener("click", (event) => {
          event.preventDefault();
          event.stopPropagation();
          downloadImageAsset(image);
        });
      }
      if (this.options.onRemove) {
        const remove = wrapper.createEl("button", {
          cls: "asys__image-remove asys__image-action asys__icon clickable-icon"
        });
        setIcon(remove, "x");
        remove.ariaLabel = "Remove image";
        remove.addEventListener("click", (event) => {
          var _a, _b;
          event.preventDefault();
          event.stopPropagation();
          (_b = (_a = this.options).onRemove) == null ? void 0 : _b.call(_a, index);
        });
      }
      if (this.options.onReorder) {
        wrapper.setAttribute("draggable", "true");
        wrapper.addEventListener("dragstart", (event) => {
          var _a, _b;
          this.dragIndex = index;
          (_a = event.dataTransfer) == null ? void 0 : _a.setData(IMAGE_DRAG_TYPE, "true");
          if (event.dataTransfer) {
            event.dataTransfer.effectAllowed = "move";
          }
          const rect = img.getBoundingClientRect();
          const width = rect.width;
          const height = rect.height;
          const preview = img.cloneNode(true);
          preview.addClass("asys__image-drag-preview");
          preview.style.width = `${width}px`;
          preview.style.height = `${height}px`;
          document.body.appendChild(preview);
          this.dragPreviewEl = preview;
          (_b = event.dataTransfer) == null ? void 0 : _b.setDragImage(
            preview,
            width / 2,
            height / 2
          );
          wrapper.addClass("asys__image-placeholder");
        });
        wrapper.addEventListener("dragend", (_event) => {
          this.resetDragState();
        });
      }
    });
  }
  isOurDrag(event) {
    var _a;
    const types = (_a = event.dataTransfer) == null ? void 0 : _a.types;
    return !!types && Array.from(types).includes(IMAGE_DRAG_TYPE);
  }
};
var ImageModal = class extends import_obsidian2.Modal {
  constructor(app, images, selectedIndex) {
    super(app);
    this.images = images;
    this.mainImageEl = null;
    this.thumbs = null;
    this.keydownHandler = (event) => {
      if (this.images.length <= 1)
        return;
      if (event.key === "ArrowLeft") {
        event.preventDefault();
        this.setCurrentImage(
          (this.currentIndex + this.images.length - 1) % this.images.length
        );
      } else if (event.key === "ArrowRight") {
        event.preventDefault();
        this.setCurrentImage((this.currentIndex + 1) % this.images.length);
      }
    };
    this.currentIndex = this.images.length == 0 ? 0 : Math.min(Math.max(selectedIndex, 0), this.images.length - 1);
  }
  centerSelectedThumb(instant = false) {
    var _a;
    (_a = this.thumbs) == null ? void 0 : _a.centerSelected(instant);
  }
  setCurrentImage(index) {
    if (index < 0 || index >= this.images.length)
      return;
    this.currentIndex = index;
    const asset = this.images[this.currentIndex];
    if (this.mainImageEl) {
      this.mainImageEl.src = asset.url;
    }
    if (this.thumbs) {
      this.thumbs.setSelectedIndex(index);
    }
  }
  onOpen() {
    const { contentEl } = this;
    this.containerEl.addClass("asys__image-modal-container");
    contentEl.empty();
    if (this.images.length == 0) {
      this.close();
      return;
    }
    const containerEl = contentEl.createDiv({ cls: "asys__image-modal" });
    if (this.images.length === 1) {
      containerEl.addClass("asys__image-single");
    }
    const mainEl = containerEl.createDiv({ cls: "asys__image-modal-main" });
    const asset = this.images[this.currentIndex];
    this.mainImageEl = mainEl.createEl("img", {
      attr: { src: asset.url }
    });
    if (this.images.length > 1) {
      const thumbsContainer = containerEl.createDiv({
        cls: "asys__images asys__image-modal-images"
      });
      this.thumbs = new ImageList(thumbsContainer, {
        showSelection: true,
        selectedIndex: this.currentIndex,
        onClick: (_, index) => this.setCurrentImage(index)
      });
      this.thumbs.setImages(this.images, this.currentIndex);
      this.centerSelectedThumb(true);
    } else {
      this.thumbs = null;
    }
    window.addEventListener("keydown", this.keydownHandler);
  }
  onClose() {
    window.removeEventListener("keydown", this.keydownHandler);
    this.contentEl.empty();
    this.contentEl.removeClass("asys__image-modal");
    this.containerEl.removeClass("asys__image-modal-container");
    this.thumbs = null;
  }
};
var DATA_URL_REGEX = /^data:([^;]+);base64,(.+)$/i;
async function imageAssetFromDataUrl(dataUrl) {
  const match = DATA_URL_REGEX.exec(dataUrl.trim());
  if (!match) {
    throw new Error("Invalid data URL");
  }
  const mime = match[1];
  const base64 = match[2];
  const binary = atob(base64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) {
    bytes[i] = binary.charCodeAt(i);
  }
  const blob = new Blob([bytes], { type: mime });
  const url = URL.createObjectURL(blob);
  return { blob, mime, url };
}
async function imageAssetToDataUrl(image) {
  const buffer = await image.blob.arrayBuffer();
  const bytes = new Uint8Array(buffer);
  let binary = "";
  for (let i = 0; i < bytes.length; i++) {
    binary += String.fromCharCode(bytes[i]);
  }
  const base64 = btoa(binary);
  return `data:${image.mime};base64,${base64}`;
}
function guessMimeFromPath(filePath, fallback = "application/octet-stream") {
  var _a;
  const ext = (_a = filePath.split(".").pop()) == null ? void 0 : _a.toLowerCase();
  const map = {
    png: "image/png",
    jpg: "image/jpeg",
    jpeg: "image/jpeg",
    webp: "image/webp",
    gif: "image/gif",
    bmp: "image/bmp",
    avif: "image/avif",
    svg: "image/svg+xml"
  };
  return ext && map[ext] || fallback;
}
async function imageAssetToFS(image, filePath) {
  const buffer = Buffer.from(await image.blob.arrayBuffer());
  await fs.promises.writeFile(filePath, buffer);
}
async function imageAssetFromBlob(blob) {
  const url = URL.createObjectURL(blob);
  return { blob, mime: blob.type, url };
}
async function imageAssetFromFile(file) {
  const arrayBuffer = await file.arrayBuffer();
  const blob = new Blob([arrayBuffer], { type: file.type });
  const url = URL.createObjectURL(blob);
  return { blob, mime: file.type, url };
}
function addImageDropTarget(element, opts) {
  const activeClass = "asys__drop-active";
  const canAcceptDrop = (event) => {
    var _a, _b, _c, _d;
    if (opts.canAccept && !opts.canAccept()) {
      return false;
    }
    const data = event.dataTransfer;
    if (!data)
      return false;
    const items = Array.from((_a = data.items) != null ? _a : []);
    const hasFileItem = items.some(
      (item) => item.kind === "file" && (item.type.startsWith("image/") || item.type === "")
    );
    const hasFileType = Array.from((_b = data.types) != null ? _b : []).includes("Files") || ((_d = (_c = data.files) == null ? void 0 : _c.length) != null ? _d : 0) > 0;
    return hasFileItem || hasFileType;
  };
  const clear = () => {
    element.removeClass(activeClass);
  };
  element.addEventListener("dragenter", (event) => {
    if (!canAcceptDrop(event))
      return;
    event.preventDefault();
    element.addClass(activeClass);
  });
  element.addEventListener("dragover", (event) => {
    if (!canAcceptDrop(event))
      return;
    event.preventDefault();
    if (event.dataTransfer) {
      event.dataTransfer.dropEffect = "copy";
    }
    element.addClass(activeClass);
  });
  element.addEventListener("dragleave", (_event) => {
    clear();
  });
  element.addEventListener("drop", (event) => {
    var _a, _b;
    if (!canAcceptDrop(event))
      return;
    event.preventDefault();
    const files = Array.from((_b = (_a = event.dataTransfer) == null ? void 0 : _a.files) != null ? _b : []).filter(
      (file) => file.type.startsWith("image/")
    );
    if (files.length === 0) {
      clear();
      return;
    }
    Promise.all(files.map((file) => imageAssetFromFile(file))).then((assets) => {
      opts.onImages(assets);
    }).catch((err) => {
      console.error("Failed to handle dropped image", err);
    }).finally(() => {
      clear();
    });
  });
}

// src/api.ts
function sanitize(text) {
  return [...text].map((c) => /^[\x00-\x7F]$/.test(c) ? c : c.split("").map((a) => "\\u" + a.charCodeAt(0).toString(16).padStart(4, "0")).join("")).join("");
}
function formatSentence(text) {
  text = text.charAt(0).toUpperCase() + text.slice(1);
  if (text.charAt(text.length - 1) != ".") {
    text += ".";
  }
  return text;
}
function joinEndpoint(base, path2) {
  if (base.charAt(base.length - 1) == path2.charAt(0)) {
    base = base.slice(0, -1);
  }
  return base + path2;
}
var CHAT_PATH = "/v1/chat/completions";
var MODELS_PATH = "/v1/models";
var ERROR_SUFFIX = "Press to dismiss.";
function parseCapabilities(value) {
  var _a, _b, _c;
  if (!value || typeof value !== "object") {
    return { reasoning: false, images: false };
  }
  const reasoningFlag = (_a = value == null ? void 0 : value.supported_parameters) == null ? void 0 : _a.includes("reasoning");
  const imagesFlag = (_c = (_b = value == null ? void 0 : value.architecture) == null ? void 0 : _b.input_modalities) == null ? void 0 : _c.includes("image");
  return {
    reasoning: reasoningFlag,
    images: imagesFlag
  };
}
var OpenAICompatibleAPI = class {
  constructor(endpoint, model, settings = {}) {
    this.request = null;
    this.closed = false;
    this.endpoint = endpoint;
    this.model = model;
    this.settings = settings;
    this.events = new import_node_events.EventEmitter();
  }
  getChatEndpoint() {
    return joinEndpoint(this.endpoint, CHAT_PATH);
  }
  getModelsEndpoint() {
    return joinEndpoint(this.endpoint, MODELS_PATH);
  }
  getBaseHeaders() {
    const headers = {
      accept: "application/json"
    };
    const apiKey = this.settings.apiKey;
    headers.authorization = `Bearer ${apiKey}`;
    return headers;
  }
  getHeaders(body) {
    const headers = this.getBaseHeaders();
    headers["content-type"] = "application/json";
    headers["content-length"] = Buffer.byteLength(body, "utf8").toString();
    return headers;
  }
  adjustContent(content) {
    if (this.settings.apiEndpoint != "https://openrouter.ai/api") {
      if (content.reasoning && content.reasoning.effort) {
        content.reasoning_effort = content.reasoning.effort;
        delete content.reasoning;
      }
    }
    return content;
  }
  async getBody(history, target) {
    var _a;
    const messages = await this.getMessages(history, target);
    const parameters = (_a = this.settings.parameters) != null ? _a : {};
    const { systemPrompt, additional, ...requestSettings } = parameters;
    let additionalParams = null;
    if (typeof additional === "string") {
      try {
        const parsed = JSON.parse(additional);
        if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
          additionalParams = parsed;
        }
      } catch (err) {
        console.warn("Invalid additional parameters JSON", err);
      }
    }
    if (typeof systemPrompt === "string" && systemPrompt.trim().length > 0) {
      messages.unshift({
        role: "system",
        content: systemPrompt
      });
    }
    const request2 = {
      stream: true,
      model: this.model.id,
      ...requestSettings,
      ...additionalParams != null ? additionalParams : {}
    };
    console.log("Request: ", request2);
    const content = this.adjustContent({
      ...request2,
      messages
    });
    console.log("Content: ", content);
    const body = sanitize(JSON.stringify(content));
    return body;
  }
  async getMessages(history, target) {
    var _a, _b;
    const includeImages = this.model.capabilities.images;
    let messages = [];
    let documents = [];
    let documentImages = [];
    let omittedImagesCount = 0;
    const resolveSelectedSwipe = (entry) => {
      const { index, swipes } = entry;
      if (Number.isInteger(index) && index >= 0 && index < swipes.length) {
        return swipes[index];
      }
      if (Number.isInteger(index) && index === swipes.length && entry.new) {
        return entry.new;
      }
      if (swipes.length > 0) {
        entry.index = swipes.length - 1;
        return swipes[entry.index];
      }
      return entry.new;
    };
    for (const [, document2] of history.documents.entries()) {
      if (document2.mute) {
        continue;
      }
      let content = "";
      try {
        const adapter = (_a = history.app) == null ? void 0 : _a.vault.adapter;
        const binary = new Uint8Array(
          await adapter.readBinary(document2.file.path)
        );
        const mime = guessMimeFromPath(
          document2.file.path,
          "application/octet-stream"
        );
        if (mime.startsWith("image/")) {
          if (includeImages) {
            content = `IMAGE ${documentImages.length} (${mime})`;
            const image = await imageAssetFromBlob(
              new Blob([binary], { type: mime })
            );
            documentImages.push(await imageAssetToDataUrl(image));
          } else {
            content = `OMITTED`;
            omittedImagesCount++;
          }
        } else {
          try {
            content = new TextDecoder("utf-8", {
              fatal: true
            }).decode(binary);
          } catch (e) {
            content = "UNKNOWN BINARY FORMAT";
          }
        }
      } catch (err) {
        console.error("Failed to read document content", err);
        content = "ERROR READING DOCUMENT";
      }
      documents.push(
        `BEGIN DOCUMENT (${document2.file.path})
${content}
END DOCUMENT`
      );
    }
    for (const [, entry] of history.entries.entries()) {
      if (target == entry) {
        break;
      }
      const swipe = resolveSelectedSwipe(entry);
      if (!swipe) {
        continue;
      }
      const text = swipe.content;
      const images = (_b = swipe.images) != null ? _b : [];
      let content = text;
      if (includeImages) {
        const imageUrls = await Promise.all(
          images.map((img) => imageAssetToDataUrl(img))
        );
        content = [
          {
            type: "text",
            text
          },
          ...imageUrls.map((url) => ({
            type: "image_url",
            image_url: { url }
          }))
        ];
      }
      messages.push({
        role: entry.user ? "user" : "assistant",
        content
      });
    }
    if (messages.length == 0) {
      messages.push({
        role: "user",
        content: ""
      });
    }
    if (typeof messages[0].content === "string") {
      messages[0].content = [
        {
          type: "text",
          text: messages[0].content
        }
      ];
    }
    let prefix = "BEGIN DOCUMENTS\n";
    if (documents.length > 0) {
      prefix += documents.join("\n") + "\n";
    } else {
      prefix += "NO SHARED DOCUMENTS\n";
    }
    if (documentImages.length > 0) {
      if (includeImages) {
        messages[0].content.splice(
          1,
          0,
          ...documentImages.map((url) => ({
            type: "image_url",
            image_url: { url }
          }))
        );
      } else {
        omittedImagesCount += documentImages.length;
      }
    }
    if (omittedImagesCount > 0) {
      prefix += `WARNING: IMAGE DATA OMITTED (${omittedImagesCount} IMAGES). TELL THE USER TO CHECK THEIR SETTINGS.
`;
    }
    prefix += "END DOCUMENTS\nBEGIN CHAT\n";
    const firstContent = messages[0].content[0];
    firstContent.text = `${prefix}${firstContent.text}`;
    return messages;
  }
  emitContentDelta(delta) {
    var _a, _b, _c;
    const pushText = (text) => {
      if (typeof text === "string" && text.length > 0) {
        this.events.emit("text", text);
      }
    };
    const pushImage = (imageUrl) => {
      if (typeof imageUrl === "string" && imageUrl.length > 0) {
        this.events.emit("image", imageUrl);
      }
    };
    const pushReasoning = (reasoning2) => {
      if (typeof reasoning2 === "string" && reasoning2.length > 0) {
        this.events.emit("reasoning", reasoning2);
      }
    };
    const content = delta == null ? void 0 : delta.content;
    if (typeof content === "string") {
      pushText(content);
    } else if (Array.isArray(content)) {
      for (const part of content) {
        if ((part == null ? void 0 : part.type) === "text") {
          pushText(part.text);
        } else if ((part == null ? void 0 : part.type) === "image_url") {
          pushImage((_a = part.image_url) == null ? void 0 : _a.url);
        }
      }
    }
    const reasoning = delta == null ? void 0 : delta.reasoning;
    if (typeof reasoning === "string") {
      pushReasoning(reasoning);
    } else if (Array.isArray(reasoning)) {
      for (const part of reasoning) {
        if ((part == null ? void 0 : part.type) === "text") {
          pushReasoning(part.text);
        }
      }
    }
    const images = delta == null ? void 0 : delta.images;
    if (Array.isArray(images)) {
      for (const image of images) {
        pushImage((_b = image == null ? void 0 : image.image_url) == null ? void 0 : _b.url);
      }
    } else {
      pushImage((_c = delta == null ? void 0 : delta.image_url) == null ? void 0 : _c.url);
    }
  }
  async handleChunk(chunk, parser) {
    try {
      parser.feed(chunk);
    } catch (e) {
    }
  }
  async send(history, target) {
    const url = this.getChatEndpoint();
    const body = await this.getBody(history, target);
    let headers = this.getHeaders(body);
    const parser = createParser((event) => {
      var _a, _b;
      if (event.type != "event")
        return;
      if (event.data === "[DONE]") {
        return;
      }
      let response = null;
      try {
        response = JSON.parse(event.data);
      } catch (e) {
        return;
      }
      if (response.object !== "chat.completion.chunk") {
        return;
      }
      const delta = (_b = (_a = response.choices) == null ? void 0 : _a[0]) == null ? void 0 : _b.delta;
      if (delta) {
        this.emitContentDelta(delta);
      }
    });
    var request_fn = import_node_https.request;
    if (url.startsWith("http://")) {
      request_fn = import_node_http.request;
    }
    this.request = request_fn(
      url,
      {
        method: "POST",
        headers
      },
      async (response) => {
        var _a;
        const status = (_a = response.statusCode) != null ? _a : 0;
        this.events.emit("status", status);
        if (status == 200) {
          response.socket.setTimeout(0);
          response.setEncoding("utf8");
          response.on("data", async (chunk) => {
            await this.handleChunk(chunk, parser);
          });
          response.on("end", () => {
            this.events.emit("done");
          });
        } else {
          let data = "";
          response.on("data", (chunk) => {
            data += chunk;
          });
          response.on("close", () => {
            let title = `HTTP ${status} ${HTTPStatus[status]}`;
            let details = ERROR_SUFFIX;
            try {
              let err = formatSentence(
                JSON.parse(data).error.message
              );
              details = `${err}
${details}`;
            } catch (e) {
            }
            this.events.emit("error", `${title}
${details}`);
          });
        }
      }
    );
    this.request.on("error", (e) => {
      var _a;
      if (this.closed)
        return;
      this.events.emit(
        "error",
        `Request Failed
${e.name}: ${formatSentence(
          e.message
        )}
${ERROR_SUFFIX}`
      );
      (_a = this.request) == null ? void 0 : _a.destroy();
      this.closed = true;
    });
    this.request.on("timeout", (e) => {
      var _a;
      if (this.closed)
        return;
      this.events.emit(
        "error",
        `Request Failed
Timeout
${ERROR_SUFFIX}`
      );
      (_a = this.request) == null ? void 0 : _a.destroy();
      this.closed = true;
    });
    this.request.on("close", () => {
      this.closed = true;
      this.events.emit("close");
    });
    this.request.setTimeout(20 * 1e3);
    this.request.write(Buffer.from(body, "utf8"));
    this.request.end();
  }
  async abort() {
    if (this.request && !this.closed) {
      this.events.emit("abort");
      this.request.destroy();
    }
  }
  async listModels() {
    const url = this.getModelsEndpoint();
    const headers = this.getBaseHeaders();
    return new Promise((resolve2) => {
      const request_fn = url.startsWith("http://") ? import_node_http.request : import_node_https.request;
      const req = request_fn(
        url,
        {
          method: "GET",
          headers
        },
        (response) => {
          var _a;
          const status = (_a = response.statusCode) != null ? _a : 0;
          if (status < 200 || status >= 300) {
            console.error("List models status", status);
            resolve2(
              new Error(`HTTP ${status} ${HTTPStatus[status]}`)
            );
            return;
          }
          const chunks = [];
          response.on("data", (chunk) => {
            chunks.push(
              Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk)
            );
          });
          response.on("end", () => {
            try {
              const data = Buffer.concat(chunks).toString("utf8");
              const payload = JSON.parse(data);
              const items = Array.isArray(payload == null ? void 0 : payload.data) ? payload.data : [];
              const models = [];
              for (const item of items) {
                if (!item || typeof item.id !== "string") {
                  continue;
                }
                models.push({
                  id: item.id,
                  capabilities: parseCapabilities(item)
                });
              }
              resolve2(models);
            } catch (error) {
              console.error("List models parse error", error);
              resolve2(new Error("Request error: Parse failed"));
            }
          });
        }
      );
      req.on("error", (err) => {
        console.error("List models error", err);
        resolve2(new Error(`Request error: ${err.message}`));
      });
      req.on("timeout", (err) => {
        console.error("List models timeout", err);
        resolve2(new Error("Request timeout"));
      });
      req.end();
    });
  }
};
function getAPI(settings) {
  var _a, _b, _c, _d, _e, _f, _g;
  const modelId = (_c = (_b = (_a = settings.apiModel) == null ? void 0 : _a.id) == null ? void 0 : _b.trim()) != null ? _c : "";
  if (modelId.length === 0) {
    return null;
  }
  const endpoint = typeof settings.apiEndpoint === "string" ? settings.apiEndpoint.trim() : "";
  if (endpoint.length === 0) {
    return null;
  }
  const model = {
    id: modelId,
    capabilities: {
      reasoning: ((_e = (_d = settings.apiModel) == null ? void 0 : _d.capabilities) == null ? void 0 : _e.reasoning) === true,
      images: ((_g = (_f = settings.apiModel) == null ? void 0 : _f.capabilities) == null ? void 0 : _g.images) === true
    }
  };
  return new OpenAICompatibleAPI(
    endpoint,
    model,
    settings
  );
}

// src/view.ts
var VIEW_TYPE_CHAT = "arenasys-ai-chat-view";
var ChatView = class extends import_obsidian3.ItemView {
  constructor(leaf, profiles) {
    super(leaf);
    this.imageLists = /* @__PURE__ */ new WeakMap();
    this.profiles = profiles;
  }
  openImageModal(image, galleryImages) {
    const images = galleryImages != null ? galleryImages : this.getVisibleImages();
    let selectedIndex = images.findIndex((img) => img.url === image.url);
    if (selectedIndex === -1) {
      images.push(image);
      selectedIndex = images.length - 1;
    }
    new ImageModal(this.app, images, selectedIndex).open();
  }
  getVisibleImages() {
    var _a, _b, _c;
    const images = [];
    for (const entry of (_b = (_a = this.history) == null ? void 0 : _a.entries) != null ? _b : []) {
      const swipe = (_c = entry.new) != null ? _c : entry.index >= 0 && entry.index < entry.swipes.length ? entry.swipes[entry.index] : null;
      if (!(swipe == null ? void 0 : swipe.images))
        continue;
      images.push(...swipe.images.filter(Boolean));
    }
    return images;
  }
  getSettings() {
    return this.profiles.settings[this.profiles.current];
  }
  getViewType() {
    return VIEW_TYPE_CHAT;
  }
  getDisplayText() {
    return "Chat";
  }
  getIcon() {
    return "message-square";
  }
  setWorking(working) {
    this.working = working;
    this.syncGenerateButtonToDom();
  }
  async setText(el, text) {
    el.empty();
    const lines = text.split("\n");
    for (const [index, line] of lines.entries()) {
      el.appendText(line);
      if (index != lines.length - 1) {
        el.createEl("br");
      }
    }
  }
  async setMarkdown(el, text) {
    const tmp = document.createElement("div");
    await import_obsidian3.MarkdownRenderer.render(this.app, text, tmp, "", this);
    el.empty();
    const length = tmp.children.length;
    for (var i = 0; i < length; i++) {
      const thisNode = tmp.children[0];
      const nextNode = tmp.children[1];
      el.appendChild(thisNode);
      if ((thisNode == null ? void 0 : thisNode.tagName) == "P" && (nextNode == null ? void 0 : nextNode.tagName) == "P") {
        el.appendChild(document.createElement("br"));
      }
    }
  }
  ensureImageList(container, options) {
    let list = this.imageLists.get(container);
    if (!list) {
      list = new ImageList(container, options);
      this.imageLists.set(container, list);
    } else {
      list.updateOptions(options);
    }
    return list;
  }
  syncInputImages() {
    var _a;
    if (!this.inputImagesContainer) {
      return;
    }
    const list = this.ensureImageList(this.inputImagesContainer, {
      onClick: (image) => this.openImageModal(image, this.inputImages),
      onRemove: (index) => {
        this.inputImages.splice(index, 1);
        this.syncInputImages();
      },
      onReorder: (images) => {
        this.inputImages = images;
      }
    });
    list.setImages((_a = this.inputImages) != null ? _a : []);
  }
  addPlainPaste(element, onImage) {
    element.addEventListener("paste", (event) => {
      var _a;
      const clipboard = event.clipboardData;
      if (!clipboard) {
        return;
      }
      const files = Array.from((_a = clipboard.files) != null ? _a : []).filter(
        (file) => file.type.startsWith("image/")
      );
      const text = clipboard.getData("text/plain");
      if (text || files.length > 0) {
        event.preventDefault();
      }
      if (text) {
        document.execCommand("insertText", false, text);
      }
      for (const file of files) {
        imageAssetFromFile(file).then((asset) => {
          onImage == null ? void 0 : onImage(asset);
        }).catch((err) => {
          console.error("Failed to parse pasted image", err);
        });
      }
    });
  }
  addEntry(entry) {
    const container = this.entryContainer;
    entry.swipes = entry.swipes.map((swipe) => {
      var _a;
      return {
        ...swipe,
        images: (_a = swipe.images) != null ? _a : []
      };
    });
    entry.element = container.createEl("div", { cls: "asys__entry" });
    entry.element.addClass(entry.user ? "asys__right" : "asys__left");
    const inner = entry.element.createEl("div", {
      cls: "asys__entry_inner"
    });
    const controls = inner.createEl("div", {
      cls: "asys__controls"
    });
    const contentWrapper = inner.createEl("div", {
      cls: "asys__content"
    });
    const content = contentWrapper.createDiv({
      cls: "asys__content-text"
    });
    const images = contentWrapper.createDiv({
      cls: "asys__images asys__hidden"
    });
    const removeOutsidePointerListener = () => {
      const handler = entry._outsidePointerHandler;
      if (handler) {
        document.removeEventListener("pointerdown", handler, true);
        delete entry._outsidePointerHandler;
      }
    };
    const finishEditing = () => {
      if (!entry.edit) {
        return;
      }
      entry.edit = false;
      this.editOriginal = null;
      removeOutsidePointerListener();
      this.syncEntryToDom(entry);
    };
    const revertEditing = () => {
      var _a;
      if (!entry.edit) {
        return;
      }
      const current = entry.swipes[entry.index];
      if (current && this.editOriginal) {
        current.content = this.editOriginal.content;
        current.images = [...(_a = this.editOriginal.images) != null ? _a : []];
        current.thoughts = this.editOriginal.thoughts;
      }
      entry.edit = false;
      this.editOriginal = null;
      removeOutsidePointerListener();
      this.syncEntryToDom(entry);
    };
    const addOutsidePointerListener = () => {
      removeOutsidePointerListener();
      const handler = (event) => {
        const target = event.target;
        const targetButton = target == null ? void 0 : target.closest("button");
        const insideContent = (target == null ? void 0 : target.closest(".asys__content")) === contentWrapper;
        const isEditButton = targetButton === editButton;
        const isTrashButton = targetButton === trashButton;
        if (!insideContent && !isEditButton && !isTrashButton) {
          finishEditing();
        }
      };
      entry._outsidePointerHandler = handler;
      document.addEventListener("pointerdown", handler, true);
    };
    const startEditing = () => {
      var _a;
      if (entry.edit) {
        return;
      }
      entry.reasoning = false;
      const swipe = entry.swipes[entry.index];
      this.editOriginal = swipe ? { ...swipe, images: [...(_a = swipe.images) != null ? _a : []] } : null;
      entry.edit = true;
      this.syncEntryToDom(entry);
      addOutsidePointerListener();
      content.focus();
    };
    content.addEventListener("input", (event) => {
      this.syncEntryFromDom(entry);
    });
    let reasoningButton = null;
    if (!entry.user) {
      reasoningButton = controls.createEl("button", {
        cls: "asys__icon clickable-icon"
      });
      setIcon(reasoningButton, "brain");
      reasoningButton.addEventListener("click", (event) => {
        const currentSwipe = entry.swipes[entry.index];
        if (!entry.new && (currentSwipe == null ? void 0 : currentSwipe.thoughts) && !entry.edit) {
          entry.reasoning = !entry.reasoning;
          this.syncEntryToDom(entry);
        }
      });
    }
    const editButton = controls.createEl("button", {
      cls: "asys__icon clickable-icon"
    });
    setIcon(editButton, "more-horizontal");
    editButton.addEventListener("click", (event) => {
      if (entry.edit) {
        finishEditing();
      } else {
        startEditing();
      }
    });
    if (!entry.user) {
      const label = controls.createEl("span", { cls: "asys__label" });
      const leftButton = controls.createEl("button", {
        cls: "asys__icon clickable-icon"
      });
      setIcon(leftButton, "chevron-left");
      leftButton.addEventListener("click", (event) => {
        if (entry.index - 1 >= 0) {
          entry.index -= 1;
          this.syncEntryToDom(entry);
        }
      });
      const rightButton = controls.createEl("button", {
        cls: "asys__icon clickable-icon"
      });
      setIcon(rightButton, "chevron-right");
      rightButton.addEventListener("click", (event) => {
        if (entry.index + 1 < entry.swipes.length) {
          entry.index += 1;
          this.syncEntryToDom(entry);
        } else {
          this.redoResponse(entry);
        }
      });
    }
    const trashButton = controls.createEl("button", {
      cls: "asys__icon clickable-icon asys__red"
    });
    let clicked = false;
    setIcon(trashButton, "x");
    trashButton.addEventListener("click", (event) => {
      if (entry.edit) {
        revertEditing();
        return;
      }
      if (clicked) {
        this.removeEntry(entry);
      } else {
        clicked = true;
        setIcon(trashButton, "check");
        setTimeout(() => {
          clicked = false;
          setIcon(trashButton, "x");
        }, 500);
      }
    });
    trashButton.addEventListener("contextmenu", (event) => {
      if (trashButton.ariaDisabled === "true") {
        return;
      }
      this.entryMenuIndex = this.history.entries.indexOf(entry);
      const rect = trashButton.getBoundingClientRect();
      this.entryMenu.showAtPosition({ x: rect.right, y: rect.bottom });
    });
    this.addPlainPaste(content, (image) => {
      var _a;
      if (!entry.edit) {
        return;
      }
      const swipe = entry.swipes[entry.index];
      swipe.images = (_a = swipe.images) != null ? _a : [];
      swipe.images.push(image);
      this.syncEntryToDom(entry);
    });
    addImageDropTarget(entry.element, {
      canAccept: () => entry.edit,
      onImages: (images2) => {
        var _a;
        const swipe = entry.swipes[entry.index];
        if (!swipe)
          return;
        swipe.images = (_a = swipe.images) != null ? _a : [];
        swipe.images.push(...images2);
        this.syncEntryToDom(entry);
      }
    });
    this.syncEntryToDom(entry);
    this.history.entries.push(entry);
    return entry;
  }
  removeEntry(entry) {
    try {
      this.entryContainer.removeChild(entry.element);
      this.history.entries.remove(entry);
    } catch (e) {
    }
  }
  cleanEntry(entry) {
    entry.new = null;
    if (entry.swipes.length == 0) {
      this.removeEntry(entry);
    } else {
      entry.index = entry.swipes.length - 1;
      this.syncEntryToDom(entry);
    }
  }
  finishEntry(entry) {
    if (entry.new != null) {
      entry.swipes.push(entry.new);
      entry.index = entry.swipes.length - 1;
      entry.new = null;
      this.syncEntryToDom(entry);
    }
  }
  async syncEntryToDom(entry) {
    var _a, _b, _c, _d;
    const inner = entry.element.children[0];
    const controls = inner.children[0];
    const editButton = controls.children[entry.user ? 0 : 1];
    const trashButton = controls.lastElementChild;
    const reasoningButton = entry.user ? null : controls.children[0];
    const contentWrapper = inner.children[1];
    const content = contentWrapper.children[0];
    const images = contentWrapper.children[1];
    const editing = content.getAttribute("contenteditable") == "true";
    if (editing && !entry.edit) {
      (_a = entry.element) == null ? void 0 : _a.removeClass("asys__edit");
      setIcon(editButton, "more-horizontal");
      editButton.removeClass("asys__green");
      editButton.ariaLabel = "Edit";
      trashButton.ariaLabel = "Delete";
    }
    if (!editing && entry.edit) {
      (_b = entry.element) == null ? void 0 : _b.addClass("asys__edit");
      setIcon(editButton, "check");
      editButton.addClass("asys__green");
    }
    content.setAttribute("contenteditable", entry.edit ? "true" : "false");
    const invalid = entry.swipes.length == 0 || entry.index >= entry.swipes.length;
    var working = entry.new != null;
    var reasoning = entry.reasoning && !entry.edit;
    const currentSwipe = working ? entry.new : entry.swipes[entry.index];
    controls.setAttribute(
      "data-asys-show",
      entry.edit || reasoning ? "true" : "false"
    );
    if (invalid && !working) {
      if (entry.started) {
        setLoader(content);
      } else {
        content.setText("");
      }
    } else {
      const text = (_c = reasoning ? currentSwipe == null ? void 0 : currentSwipe.thoughts : currentSwipe == null ? void 0 : currentSwipe.content) != null ? _c : "";
      if (entry.edit) {
        await this.setText(content, text);
      } else {
        inner.setAttribute(
          "data-asys-reasoning",
          working && reasoning ? "true" : "false"
        );
        content.setAttribute(
          "data-asys-reasoning",
          reasoning ? "true" : "false"
        );
        await this.setMarkdown(content, text);
        if (reasoning) {
          inner.scrollTop = inner.scrollHeight;
        }
      }
    }
    editButton.ariaLabel = entry.edit ? "Accept" : "Edit";
    editButton.ariaDisabled = invalid || working ? "true" : "false";
    trashButton.ariaLabel = entry.edit ? "Revert" : "Delete";
    trashButton.ariaDisabled = invalid || working ? "true" : "false";
    if (!entry.user) {
      const label = controls.children[2];
      label.setText(
        entry.swipes.length == 0 ? "" : `${entry.index + 1} of ${entry.swipes.length}`
      );
      const leftButton = controls.children[3];
      leftButton.ariaDisabled = entry.index == 0 || invalid || entry.edit ? "true" : "false";
      leftButton.ariaLabel = "Previous";
      const rightButton = controls.children[4];
      rightButton.ariaDisabled = invalid || entry.edit ? "true" : "false";
      rightButton.ariaLabel = "Next";
      if (reasoningButton) {
        const currentSwipe2 = entry.swipes[entry.index];
        const reasoning2 = entry.reasoning;
        const showReasoningButton = !!(currentSwipe2 == null ? void 0 : currentSwipe2.thoughts);
        reasoningButton.classList.toggle(
          "asys__hidden",
          !showReasoningButton
        );
        reasoningButton.classList.toggle(
          "asys__green-active",
          !!reasoning2
        );
        reasoningButton.classList.toggle(
          "asys__gray-active",
          !reasoning2
        );
        reasoningButton.ariaLabel = reasoning2 ? "Reasoning" : "Hide Reasoning";
        reasoningButton.ariaDisabled = invalid || entry.edit ? "true" : "false";
      }
    }
    const imagesToRender = ((_d = currentSwipe == null ? void 0 : currentSwipe.images) != null ? _d : []).filter(
      (img) => !!img
    );
    const list = this.ensureImageList(images, {
      onClick: (image) => this.openImageModal(image),
      onRemove: entry.edit ? (index) => {
        const swipe = entry.swipes[entry.index];
        if (!(swipe == null ? void 0 : swipe.images))
          return;
        swipe.images.splice(index, 1);
        this.syncEntryToDom(entry);
      } : void 0,
      onReorder: entry.edit ? (images2) => {
        entry.swipes[entry.index].images = images2;
      } : void 0
    });
    list.setImages(imagesToRender);
  }
  syncEntryFromDom(entry) {
    const inner = entry.element.children[0];
    const contentWrapper = inner.children[1];
    const content = contentWrapper.children[0];
    entry.swipes[entry.index].content = content.innerText;
  }
  addDocument(file, append = true) {
    const row = document.createElement("div");
    row.addClass("asys__document-row");
    const element = row.createDiv({ cls: "asys__document" });
    const doc = {
      file,
      element: row,
      pin: false,
      mute: false
    };
    if (append || this.documentContainer.children.length == 0) {
      this.documentContainer.appendChild(row);
      this.history.documents.push(doc);
    } else {
      this.documentContainer.insertBefore(
        row,
        this.documentContainer.firstChild
      );
      this.history.documents.unshift(doc);
    }
    const mute = element.createEl("button", {
      cls: "asys__mute asys__toggle asys__icon clickable-icon"
    });
    mute.ariaLabel = "Hide/Unhide document";
    setIcon(mute, "eye");
    mute.addEventListener("click", (event) => {
      if (doc.mute) {
        mute.removeClass("asys__toggled");
        setIcon(mute, "eye");
        doc.mute = false;
      } else {
        mute.addClass("asys__toggled");
        setIcon(mute, "eye-off");
        doc.mute = true;
      }
    });
    const pin = element.createEl("button", {
      cls: "asys__pin asys__toggle asys__icon clickable-icon"
    });
    pin.ariaLabel = "Pin/Unpin document";
    setIcon(pin, "pin-off");
    pin.addEventListener("click", (event) => {
      if (doc.pin) {
        pin.removeClass("asys__toggled");
        doc.pin = false;
        setIcon(pin, "pin-off");
        const isFirst = doc == this.history.documents[0];
        if (!isFirst) {
          this.removeDocument(doc);
        }
        const current = this.app.workspace.getActiveFile();
        if (current) {
          this.setCurrentDocument(current);
        }
      } else {
        pin.addClass("asys__toggled");
        setIcon(pin, "pin");
        doc.pin = true;
      }
    });
    const content = element.createDiv();
    this.syncDocumentToDom(doc);
  }
  removeDocument(doc) {
    this.history.documents.remove(doc);
    this.documentContainer.removeChild(doc.element);
  }
  setCurrentDocument(file) {
    if (this.history.documents.length == 0) {
      this.addDocument(file);
    }
    const exists = this.history.documents.some((document2, index) => {
      return document2.file == file && document2.pin;
    });
    if (!exists) {
      if (!this.history.documents[0].pin) {
        this.history.documents[0].file = file;
        this.syncDocumentToDom(this.history.documents[0]);
      } else {
        this.addDocument(file, false);
      }
    } else if (!this.history.documents[0].pin) {
      const doc = this.history.documents[0];
      this.history.documents.remove(doc);
      this.documentContainer.removeChild(doc.element);
    }
  }
  syncDocumentToDom(document2) {
    const row = document2.element;
    const element = row.children[0];
    const pin = element.children[0];
    const mute = element.children[1];
    const content = element.children[2];
    content.setText(document2.file.path);
  }
  checkCurrentDocument() {
    if (this.history.documents.length > 0) {
      const document2 = this.history.documents[0];
      const element = document2.element;
      const current = element.innerText;
      const target = document2.file.path;
      if (current != target) {
        this.syncDocumentToDom(document2);
      }
    }
  }
  syncGenerateButtonToDom() {
    const button = this.inputContainer.children[0];
    if (this.working) {
      button.addClass("asys__working");
      setIcon(button, "square");
    } else {
      button.removeClass("asys__working");
      setIcon(button, "play");
    }
  }
  snapToBottom() {
    const background = this.containerEl.children[1];
    background.scrollTop = background.scrollHeight;
  }
  async hidePopup() {
    this.popupContainer.removeClass("asys__fadeIn");
    this.popupContainer.addClass("asys__fadeOut");
  }
  async showPopup(message) {
    await this.setText(this.popupContainer, message);
    this.popupContainer.removeClass("asys__fadeOut");
    this.popupContainer.addClass("asys__fadeIn");
    this.popupContainer.addEventListener("click", (event) => {
      this.hidePopup();
    });
  }
  async redoResponse(entry) {
    entry.index = entry.swipes.length;
    entry.reasoning = false;
    entry.started = false;
    entry.new = null;
    this.syncEntryToDom(entry);
    this.makeRequest(entry);
  }
  async getResponse() {
    const response = this.addEntry({
      user: false,
      edit: false,
      reasoning: false,
      new: null,
      started: false,
      index: 0,
      swipes: []
    });
    this.makeRequest(response);
  }
  async handleInput(input) {
    var _a, _b;
    const images = [...(_a = this.inputImages) != null ? _a : []];
    this.inputImages = [];
    this.syncInputImages();
    const hasText = input.trim().length > 0;
    const hasImages = images.length > 0;
    const isEmpty = !hasText && !hasImages;
    const lastEntry = this.history.entries[this.history.entries.length - 1];
    if (isEmpty) {
      if (lastEntry && lastEntry.user) {
        this.getResponse();
      }
      return;
    }
    if (lastEntry && lastEntry.user) {
      const swipe = lastEntry.swipes[lastEntry.index];
      if (hasText) {
        const separator = swipe.content.length > 0 && input.length > 0 ? "\n" : "";
        swipe.content += `${separator}${input}`;
      }
      swipe.images = (_b = swipe.images) != null ? _b : [];
      swipe.images.push(...images);
      this.syncEntryToDom(lastEntry);
      this.getResponse();
    } else {
      this.addEntry({
        user: true,
        edit: false,
        reasoning: false,
        new: null,
        started: false,
        index: 0,
        swipes: [{ content: input, images, thoughts: null }]
      });
      this.getResponse();
    }
  }
  async makeRequest(entry) {
    var _a, _b, _c;
    this.setWorking(true);
    const settings = this.getSettings();
    const modelId = (_b = (_a = settings.apiModel) == null ? void 0 : _a.id) == null ? void 0 : _b.trim();
    const endpoint = (_c = settings.apiEndpoint) == null ? void 0 : _c.trim();
    const isLast = entry == this.history.entries[this.history.entries.length - 1];
    if (!modelId) {
      this.setWorking(false);
      this.cleanEntry(entry);
      this.showPopup(
        "API model is not configured. Please set a model id in the plugin settings."
      );
      return;
    }
    if (!endpoint) {
      this.setWorking(false);
      this.cleanEntry(entry);
      this.showPopup(
        "API endpoint is not configured. Please set an endpoint in the plugin settings."
      );
      return;
    }
    const api = getAPI(settings);
    if (!api) {
      this.setWorking(false);
      this.cleanEntry(entry);
      this.showPopup(
        "Failed to initialize API client. Please verify endpoint and model settings."
      );
      return;
    }
    this.api = api;
    api.events.on("text", (text) => {
      if (text.length == 0) {
        return;
      }
      if (entry.new == null) {
        entry.new = { content: "", images: [], thoughts: null };
      }
      entry.reasoning = false;
      entry.new.content += text;
      this.syncEntryToDom(entry);
      if (isLast) {
        this.snapToBottom();
      }
    });
    api.events.on("image", async (image) => {
      var _a2, _b2;
      if (typeof image !== "string" || image.length == 0) {
        return;
      }
      try {
        const asset = await imageAssetFromDataUrl(image);
        const autoSaveFolder = (_a2 = this.getSettings().imageSaveFolder) == null ? void 0 : _a2.trim();
        if (autoSaveFolder && autoSaveFolder.length > 0) {
          autoSaveImageAsset(asset, autoSaveFolder);
        }
        if (entry.new == null) {
          entry.new = { content: "", images: [], thoughts: null };
        }
        entry.new.images = (_b2 = entry.new.images) != null ? _b2 : [];
        entry.new.images.push(asset);
        this.syncEntryToDom(entry);
        if (isLast) {
          this.snapToBottom();
        }
      } catch (err) {
        console.error("Failed to handle streamed image", err);
      }
    });
    api.events.on("reasoning", (text) => {
      if (text.length == 0) {
        return;
      }
      if (entry.reasoning == false) {
        entry.reasoning = true;
      }
      if (entry.new == null) {
        entry.new = { content: "", images: [], thoughts: "" };
      }
      if (entry.new.thoughts == null) {
        entry.new.thoughts = "";
      }
      entry.new.thoughts += text;
      this.syncEntryToDom(entry);
      if (isLast) {
        this.snapToBottom();
      }
    });
    api.events.on("status", (status) => {
      console.log(Date.now(), "Status:", status);
      if (status != 200) {
        if (isLast) {
          this.snapToBottom();
        }
      } else {
        entry.started = true;
        this.syncEntryToDom(entry);
      }
    });
    api.events.on("done", () => {
      console.log(Date.now(), "Done");
      entry.reasoning = false;
      this.finishEntry(entry);
    });
    api.events.on("error", (error) => {
      console.log(Date.now(), "Error:", error);
      this.showPopup(error);
    });
    api.events.on("abort", () => {
      console.log(Date.now(), "Aborted");
      this.finishEntry(entry);
    });
    api.events.on("close", () => {
      console.log(Date.now(), "Closed");
      this.cleanEntry(entry);
      this.setWorking(false);
    });
    await api.send(this.history, entry);
    return;
  }
  async abortRequest() {
    if (this.working && this.api) {
      await this.api.abort();
    }
  }
  async addChat() {
    this.history = {
      entries: [],
      documents: [],
      app: this.app
    };
    this.inputImages = [];
    const background = this.containerEl.children[1];
    background.addClass("asys__background");
    background.empty();
    this.entryContainer = background.createEl("div", {
      cls: "asys__entries"
    });
    const tmp = this.entryContainer.createEl("div");
    const settings = tmp.createEl("button", {
      cls: "asys__settings clickable-icon view-action"
    });
    settings.ariaLabel = "More options";
    this.documentContainer = tmp.createEl("div");
    setIcon(settings, "more-vertical");
    const settingsMenu = new import_obsidian3.Menu();
    settingsMenu.addItem((item) => {
      item.setIcon("settings");
      item.setTitle("Open settings");
      item.onClick((e) => {
        this.app.setting.open();
        if (this.app.setting.lastTabId !== PLUGIN_ID)
          this.app.setting.openTabById(PLUGIN_ID);
      });
    });
    settingsMenu.addSeparator();
    settingsMenu.addItem((item) => {
      item.setIcon("trash");
      item.setTitle("Clear chat");
      item.setWarning(true);
      item.onClick((e) => {
        this.addChat();
      });
    });
    settings.addEventListener("mousedown", (event) => {
      if (this.menuOpen) {
        this.menuSkip = true;
      }
    });
    settings.addEventListener("click", (event) => {
      if (this.menuSkip) {
        this.menuSkip = false;
        return;
      }
      const rect = settings.getBoundingClientRect();
      settingsMenu.showAtPosition({ x: rect.right, y: rect.bottom });
      this.menuOpen = true;
    });
    settingsMenu.onHide(() => {
      this.menuOpen = false;
    });
    this.entryMenu = new import_obsidian3.Menu();
    this.entryMenu.addItem((item) => {
      item.setIcon("trash");
      item.setTitle("Delete below");
      item.setWarning(true);
      item.onClick((e) => {
        let idx = this.entryMenuIndex + 1;
        while (idx < this.history.entries.length) {
          const before = this.history.entries.length;
          this.removeEntry(this.history.entries[idx]);
          if (before == this.history.entries.length) {
            break;
          }
        }
      });
    });
    const current = this.app.workspace.getActiveFile();
    if (current) {
      this.setCurrentDocument(current);
    }
    this.inputContainer = background.createDiv({
      cls: "asys__input-container"
    });
    const inputButton = this.inputContainer.createEl("button", {
      cls: "asys__icon asys__input-button clickable-icon"
    });
    inputButton.ariaLabel = "Stop";
    setIcon(inputButton, "play");
    inputButton.addEventListener("click", async (event) => {
      if (this.working) {
        this.abortRequest();
      }
    });
    const input = this.inputContainer.createDiv({ cls: "asys__input" });
    input.setAttribute("contenteditable", "true");
    input.setAttribute("placeholder", "Ask something...");
    input.addEventListener("keydown", async (event) => {
      if (event.key === "Enter" && !event.shiftKey) {
        await this.hidePopup();
        if (!this.working) {
          await this.handleInput(input.innerText);
          input.empty();
        }
        event.preventDefault();
      }
    });
    input.addEventListener("input", (event) => {
      this.snapToBottom();
      if (input.innerText == "\n") {
        input.empty();
      }
    });
    this.addPlainPaste(input, (image) => {
      this.inputImages.push(image);
      this.syncInputImages();
    });
    addImageDropTarget(this.inputContainer, {
      onImages: (images) => {
        this.inputImages.push(...images);
        this.syncInputImages();
      }
    });
    this.inputImagesContainer = this.inputContainer.createDiv({
      cls: "asys__images asys__input-images asys__hidden"
    });
    this.syncInputImages();
    this.popupContainer = background.createEl("div", {
      cls: "asys__popup asys__fadeOut"
    });
  }
  async onOpen() {
    await this.addChat();
    this.registerEvent(
      this.app.workspace.on("file-open", (file) => {
        this.setCurrentDocument(file);
      })
    );
    this.registerInterval(
      window.setInterval(() => this.checkCurrentDocument(), 1e3)
    );
  }
  async onClose() {
  }
};

// src/settings.ts
var import_obsidian4 = require("obsidian");
var DEFAULT_SETTINGS = {
  current: 0,
  names: ["Default"],
  settings: [
    {
      apiEndpoint: "https://api.openai.com",
      apiKey: "",
      apiModel: null,
      imageSaveFolder: "",
      parameters: {
        systemPrompt: "You are an assistant in Obsidian, a note-taking program. Shared notes/documents are provided. Dont show the document formatting (BEGIN DOCUMENT etc).",
        additional: ""
      }
    }
  ]
};
function cloneDefaultSettings() {
  var _a;
  const base = DEFAULT_SETTINGS.settings[0];
  return {
    ...base,
    apiModel: base.apiModel ? {
      ...base.apiModel,
      capabilities: { ...base.apiModel.capabilities }
    } : null,
    parameters: { ...(_a = base.parameters) != null ? _a : {} }
  };
}
function normalizeProfiles(profiles) {
  var _a, _b;
  if (!Array.isArray(profiles.settings) || profiles.settings.length === 0) {
    profiles.settings = [cloneDefaultSettings()];
  }
  if (!Array.isArray(profiles.names) || profiles.names.length === 0) {
    profiles.names = [...DEFAULT_SETTINGS.names];
  }
  const defaults = cloneDefaultSettings();
  const defaultCapabilities = { reasoning: false, images: false };
  const defaultParameters = (_a = defaults.parameters) != null ? _a : {};
  for (let i = 0; i < profiles.settings.length; i++) {
    const incoming = profiles.settings[i];
    if (!incoming || typeof incoming !== "object") {
      profiles.settings[i] = cloneDefaultSettings();
      continue;
    }
    const normalized = {
      ...cloneDefaultSettings(),
      parameters: { ...defaultParameters }
    };
    if (typeof incoming.apiEndpoint === "string") {
      normalized.apiEndpoint = incoming.apiEndpoint;
    }
    if (typeof incoming.apiKey === "string") {
      normalized.apiKey = incoming.apiKey;
    }
    if (typeof incoming.systemPrompt === "string") {
      incoming.parameters = { systemPrompt: incoming.systemPrompt };
    }
    if (incoming.parameters != null && typeof incoming.parameters === "object") {
      normalized.parameters = {
        ...defaultParameters,
        ...incoming.parameters
      };
    }
    const rawModel = incoming.apiModel;
    if (rawModel == null) {
      normalized.apiModel = null;
    } else {
      let modelId = typeof rawModel === "string" ? rawModel : rawModel == null ? void 0 : rawModel.id;
      if (modelId === "custom") {
        const customId = typeof incoming.apiModelCustom === "string" ? incoming.apiModelCustom : "";
        modelId = customId;
      }
      if (typeof modelId !== "string") {
        modelId = "";
      }
      const caps = (_b = rawModel == null ? void 0 : rawModel.capabilities) != null ? _b : {};
      normalized.apiModel = {
        id: modelId,
        capabilities: {
          reasoning: caps.reasoning === true ? true : caps.reasoning === false ? false : defaultCapabilities.reasoning,
          images: caps.images === true ? true : caps.images === false ? false : defaultCapabilities.images
        }
      };
    }
    if (typeof incoming.imageSaveFolder === "string") {
      normalized.imageSaveFolder = incoming.imageSaveFolder;
    }
    profiles.settings[i] = normalized;
  }
  if (profiles.names.length < profiles.settings.length) {
    const start = profiles.names.length;
    for (let i = start; i < profiles.settings.length; i++) {
      profiles.names.push(`Profile ${i + 1}`);
    }
  }
  if (typeof profiles.current !== "number" || profiles.current < 0 || profiles.current >= profiles.settings.length) {
    profiles.current = 0;
  }
}
var ChatSettingTab = class extends import_obsidian4.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.models = [];
    this.modelSearch = "";
    this.plugin = plugin;
  }
  filterModels(query) {
    const trimmed = query.trim();
    if (trimmed.length === 0) {
      return [...this.models];
    }
    const matcher = (0, import_obsidian4.prepareFuzzySearch)(trimmed);
    return this.models.filter((model) => matcher(model.id));
  }
  clearModelSearch() {
    this.models = [];
    this.modelSearch = "";
  }
  isNameAvailable(name) {
    return name.length > 0 && !this.plugin.profiles.names.includes(name);
  }
  addSetting(name = "") {
    if (name.length == 0) {
      name = DEFAULT_SETTINGS.names[0];
    }
    const settings = cloneDefaultSettings();
    this.plugin.profiles.names.push(name);
    this.plugin.profiles.settings.push(settings);
    this.plugin.profiles.current = this.plugin.profiles.names.length - 1;
    this.clearModelSearch();
  }
  display() {
    var _a, _b, _c, _d, _e, _f, _g;
    const { containerEl } = this;
    containerEl.empty();
    normalizeProfiles(this.plugin.profiles);
    const defaultCapabilities = { reasoning: false, images: false };
    const defaultParameters = {
      ...DEFAULT_SETTINGS.settings[0].parameters
    };
    const endpointPresets = {
      openai: "https://api.openai.com",
      openrouter: "https://openrouter.ai/api"
    };
    const currentIndex = this.plugin.profiles.current;
    const currentName = this.plugin.profiles.names[currentIndex];
    const currentSettings = this.plugin.profiles.settings[currentIndex];
    const currentModel = (_a = currentSettings.apiModel) != null ? _a : {
      id: "",
      capabilities: { ...defaultCapabilities }
    };
    const filteredModels = this.filterModels(this.modelSearch);
    const params = (_b = currentSettings.parameters) != null ? _b : currentSettings.parameters = { ...defaultParameters };
    const profileNames = this.plugin.profiles.names.reduce(
      (a, v) => ({ ...a, [v]: v }),
      {}
    );
    new import_obsidian4.Setting(containerEl).setHeading().setName("Profile").setClass("asys__setting-heading");
    new import_obsidian4.Setting(containerEl).setName("Current profile").addDropdown(async (component) => {
      component.selectEl.addClass("asys__setting-medium");
      component.addOptions(profileNames);
      component.setValue(currentName);
      component.onChange(async (value) => {
        const idx = this.plugin.profiles.names.indexOf(value);
        this.plugin.profiles.current = idx;
        this.clearModelSearch();
        await this.plugin.saveSettings();
        await this.display();
      });
    });
    let renameName = "";
    new import_obsidian4.Setting(containerEl).setName("Edit profile").addButton((component) => {
      component.buttonEl.addClass("asys__setting-small");
      component.setButtonText("Delete");
      component.onClick(async () => {
        this.plugin.profiles.names.splice(currentIndex, 1);
        this.plugin.profiles.settings.splice(currentIndex, 1);
        this.plugin.profiles.current = Math.max(
          currentIndex - 1,
          0
        );
        if (this.plugin.profiles.names.length == 0) {
          this.addSetting();
        }
        this.clearModelSearch();
        await this.plugin.saveSettings();
        await this.display();
      });
    }).addText((component) => {
      component.inputEl.addClass("asys__setting-name");
      component.setPlaceholder("Name");
      component.onChange((value) => {
        renameName = value;
      });
    }).addButton((component) => {
      component.buttonEl.addClass("asys__setting-small");
      component.setButtonText("Rename");
      component.onClick(async () => {
        if (this.isNameAvailable(renameName)) {
          this.plugin.profiles.names[currentIndex] = renameName;
          await this.plugin.saveSettings();
          await this.display();
        }
      });
    });
    let newName = "";
    new import_obsidian4.Setting(containerEl).setName("New profile").addText((component) => {
      component.inputEl.addClass("asys__setting-name");
      component.setPlaceholder("Name");
      component.onChange((value) => {
        newName = value;
      });
    }).addButton((component) => {
      component.buttonEl.addClass("asys__setting-small");
      component.setButtonText("New");
      component.onClick(async () => {
        if (this.isNameAvailable(newName)) {
          this.addSetting(newName);
          await this.plugin.saveSettings();
          await this.display();
        }
      });
    });
    new import_obsidian4.Setting(containerEl).setHeading().setName("Plugin").setClass("asys__setting-heading");
    new import_obsidian4.Setting(containerEl).setName("Image autosave folder").addText((text) => {
      var _a2;
      text.inputEl.addClass("asys__setting-medium");
      text.setPlaceholder("Disabled").setValue((_a2 = currentSettings.imageSaveFolder) != null ? _a2 : "").onChange(async (value) => {
        currentSettings.imageSaveFolder = value.trim();
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian4.Setting(containerEl).setHeading().setName("API").setClass("asys__setting-heading");
    let endpointInput = null;
    let modelDropdown = null;
    const presetKey = (_d = (_c = Object.entries(endpointPresets).find(
      ([, url]) => {
        var _a2;
        return url === ((_a2 = currentSettings.apiEndpoint) == null ? void 0 : _a2.trim());
      }
    )) == null ? void 0 : _c[0]) != null ? _d : "custom";
    new import_obsidian4.Setting(containerEl).setName("API Endpoint").addDropdown((component) => {
      component.addOptions({
        custom: "Custom",
        openai: "OpenAI",
        openrouter: "OpenRouter"
      });
      component.setValue(presetKey);
      component.onChange(async (value) => {
        if (value === "custom")
          return;
        const preset = endpointPresets[value];
        if (preset && endpointInput) {
          endpointInput.setValue(preset);
          currentSettings.apiEndpoint = preset;
          this.clearModelSearch();
          await this.plugin.saveSettings();
          await this.display();
        }
      });
    }).addText((component) => {
      var _a2;
      endpointInput = component;
      component.inputEl.addClass("asys__setting-medium");
      component.setPlaceholder(DEFAULT_SETTINGS.settings[0].apiEndpoint).setValue((_a2 = currentSettings.apiEndpoint) != null ? _a2 : "").onChange(async (value) => {
        currentSettings.apiEndpoint = value.trim();
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian4.Setting(containerEl).setName("API Key").addText((text) => {
      text.inputEl.addClass("asys__setting-medium");
      text.setPlaceholder("Enter your key").setValue(currentSettings.apiKey).onChange(async (value) => {
        currentSettings.apiKey = value;
        await this.plugin.saveSettings();
      });
    });
    const modelSelectRow = new import_obsidian4.Setting(containerEl).setName("API Models");
    modelSelectRow.addButton((button) => {
      button.setButtonText("Fetch");
      button.onClick(async () => {
        var _a2, _b2;
        const endpoint = (_a2 = currentSettings.apiEndpoint) == null ? void 0 : _a2.trim();
        const apiKey = (_b2 = currentSettings.apiKey) == null ? void 0 : _b2.trim();
        if (!endpoint || !apiKey) {
          new import_obsidian4.Notice("Enter API endpoint and key to fetch models.");
          return;
        }
        button.setDisabled(true);
        button.setButtonText("Fetching...");
        try {
          const api = new OpenAICompatibleAPI(
            endpoint,
            currentModel,
            {
              apiKey
            }
          );
          const models = await api.listModels();
          if (models instanceof Error) {
            new import_obsidian4.Notice(`Failed to fetch models: ${models.message}`);
          } else if (Array.isArray(models)) {
            if (models.length === 0) {
              new import_obsidian4.Notice("No models returned.");
            } else {
              this.models = models;
              new import_obsidian4.Notice(`Found ${models.length} models.`);
            }
          }
        } catch (err) {
          console.error("Fetch button", err);
          new import_obsidian4.Notice(`Failed to fetch models: ${err}`);
        } finally {
          button.setDisabled(false);
          button.setButtonText("Fetch");
          this.display();
        }
      });
    });
    modelSelectRow.addText((component) => {
      component.inputEl.addClass("asys__setting-search");
      component.setPlaceholder("Search models");
      component.setValue(this.modelSearch);
      component.onChange(async (value) => {
        var _a2;
        this.modelSearch = value;
        if (modelDropdown) {
          const filtered = this.filterModels(this.modelSearch);
          const options = {};
          if (this.modelSearch.length > 0) {
            options["search"] = `Found ${filtered.length} models`;
          }
          for (const model of filtered) {
            options[model.id] = model.id;
          }
          if (this.modelSearch.length === 0) {
            options["custom"] = "Custom";
          }
          modelDropdown.selectEl.empty();
          if (options["search"]) {
            modelDropdown.addOption("search", options["search"]);
          }
          for (const model of filtered) {
            modelDropdown.addOption(model.id, model.id);
          }
          if (options["custom"]) {
            modelDropdown.addOption("custom", "Custom");
          }
          const nextValue = ((_a2 = currentSettings.apiModel) == null ? void 0 : _a2.id) && currentSettings.apiModel.id in options ? currentSettings.apiModel.id : "";
          modelDropdown.setValue(
            this.modelSearch.length > 0 ? "search" : nextValue ? nextValue : filtered.length > 0 ? filtered[0].id : "custom"
          );
        }
      });
    });
    modelSelectRow.addDropdown((component) => {
      var _a2, _b2;
      modelDropdown = component;
      component.selectEl.addClass("asys__setting-medium");
      const hasCustom = this.modelSearch.length === 0;
      if (this.modelSearch.length > 0) {
        component.addOption(
          "search",
          `Found ${filteredModels.length} models`
        );
      }
      for (const model of filteredModels) {
        component.addOption(model.id, model.id);
      }
      if (hasCustom) {
        component.addOption("custom", "Custom");
      }
      const currentOption = filteredModels.some(
        (model) => model.id === currentModel.id
      ) ? currentModel.id : this.modelSearch.length > 0 ? "search" : hasCustom ? "custom" : (_b2 = (_a2 = filteredModels[0]) == null ? void 0 : _a2.id) != null ? _b2 : "search";
      component.setValue(currentOption);
      let lastApplied = "";
      const applySelection = async (value, force = false) => {
        if (!force && value === lastApplied) {
          return;
        }
        lastApplied = value;
        if (value === "custom" || value === "search") {
          return;
        }
        await setModelFromSelection(value);
      };
      component.onChange(async (value) => {
        await applySelection(value);
      });
    });
    new import_obsidian4.Setting(containerEl).setHeading().setName("Model").setClass("asys__setting-heading");
    let modelInput = null;
    const setModelFromSelection = async (modelId) => {
      const selected = this.models.find((m) => m.id === modelId);
      if (!selected) {
        if (modelInput) {
          modelInput.setValue(modelId != null ? modelId : "");
        }
        currentSettings.apiModel = modelId ? {
          id: modelId,
          capabilities: { ...defaultCapabilities }
        } : null;
        await this.plugin.saveSettings();
        this.display();
        return;
      }
      currentSettings.apiModel = {
        id: selected.id,
        capabilities: { ...selected.capabilities }
      };
      if (modelInput) {
        modelInput.setValue(selected.id);
      }
      await this.plugin.saveSettings();
      this.display();
    };
    new import_obsidian4.Setting(containerEl).setName("Model ID").addText((component) => {
      modelInput = component;
      component.inputEl.addClass("asys__setting-medium");
      component.setPlaceholder("gpt-4, claude-2, etc.").setValue(currentModel.id).onChange(async (value) => {
        const trimmed = value.trim();
        this.modelSearch = "";
        if (trimmed.length === 0) {
          currentSettings.apiModel = null;
        } else {
          if (!currentSettings.apiModel) {
            currentSettings.apiModel = {
              id: trimmed,
              capabilities: { ...defaultCapabilities }
            };
          } else {
            currentSettings.apiModel.id = trimmed;
          }
        }
        await this.plugin.saveSettings();
        if (modelDropdown) {
          const allModels = this.modelSearch ? filteredModels : this.models;
          const matched = allModels.some(
            (model) => model.id === trimmed
          );
          const options = {};
          for (const model of allModels) {
            options[model.id] = model.id;
          }
          options["custom"] = "Custom";
          modelDropdown.selectEl.empty();
          modelDropdown.addOptions(options);
          modelDropdown.setValue(matched ? trimmed : "custom");
        }
      });
    });
    new import_obsidian4.Setting(containerEl).setName("Supports Images").addToggle((component) => {
      component.setValue(currentModel.capabilities.images).onChange(async (value) => {
        if (!currentSettings.apiModel)
          return;
        currentSettings.apiModel.capabilities.images = value;
        await this.plugin.saveSettings();
        await this.display();
      });
    });
    new import_obsidian4.Setting(containerEl).setName("Supports Reasoning").addToggle((component) => {
      component.setValue(currentModel.capabilities.reasoning).onChange(async (value) => {
        if (!currentSettings.apiModel)
          return;
        currentSettings.apiModel.capabilities.reasoning = value;
        if (!value) {
          if (params.reasoning) {
            delete params.reasoning;
          }
        }
        await this.plugin.saveSettings();
        await this.display();
      });
    });
    new import_obsidian4.Setting(containerEl).setHeading().setName("Parameters").setClass("asys__setting-heading");
    new import_obsidian4.Setting(containerEl).setName("System prompt").addTextArea((text) => {
      var _a2;
      text.setValue((_a2 = params.systemPrompt) != null ? _a2 : "");
      text.onChange(async (value) => {
        params.systemPrompt = value;
        await this.plugin.saveSettings();
      });
      text.inputEl.addClass("asys__setting-prompt");
      text.setPlaceholder("Default");
    });
    const parseAdditional = (value) => {
      if (value.trim().length === 0) {
        return true;
      }
      try {
        const parsed = JSON.parse(value);
        return !!parsed && typeof parsed === "object" && !Array.isArray(parsed);
      } catch (e) {
        return false;
      }
    };
    const additionalSetting = new import_obsidian4.Setting(containerEl).setName(
      "Additional parameters"
    );
    const updateAdditionalStatus = (value) => {
      const unset = value.trim().length === 0;
      const valid = parseAdditional(value);
      additionalSetting.descEl.setText(
        unset ? "Unset" : valid ? "Valid" : "Invalid"
      );
      additionalSetting.descEl.toggleClass("asys__setting-unset", unset);
      additionalSetting.descEl.toggleClass(
        "asys__setting-invalid",
        !unset && !valid
      );
      additionalSetting.descEl.toggleClass(
        "asys__setting-valid",
        !unset && valid
      );
    };
    additionalSetting.addTextArea((text) => {
      const initialValue = params.additional;
      text.setValue(initialValue);
      text.onChange(async (value) => {
        params.additional = value;
        updateAdditionalStatus(value);
        await this.plugin.saveSettings();
      });
      text.inputEl.addClass("asys__setting-prompt");
      text.setPlaceholder('JSON object, e.g. {"max_tokens":500}');
    });
    updateAdditionalStatus((_e = params.additional) != null ? _e : "");
    if (currentModel.capabilities.reasoning) {
      const reasoningOptions = {
        default: "Default",
        minimal: "Minimal",
        low: "Low",
        medium: "Medium",
        high: "High"
      };
      const reasoningValue = (_g = (_f = params.reasoning) == null ? void 0 : _f.effort) != null ? _g : "default";
      new import_obsidian4.Setting(containerEl).setName("Reasoning effort").addDropdown((component) => {
        component.selectEl.addClass("asys__setting-medium");
        component.addOptions(reasoningOptions);
        component.setValue(
          reasoningOptions[reasoningValue] ? reasoningValue : "default"
        );
        component.onChange(async (value) => {
          if (value === "default") {
            delete params.reasoning;
          } else {
            params.reasoning = { effort: value };
          }
          await this.plugin.saveSettings();
        });
      });
    }
  }
};

// src/main.ts
var ChatPlugin = class extends import_obsidian5.Plugin {
  async onload() {
    await this.loadSettings();
    this.registerView(
      VIEW_TYPE_CHAT,
      (leaf) => new ChatView(leaf, this.profiles)
    );
    await this.activateView();
    this.addCommand({
      id: "ai-chat-show-chat",
      name: "Show chat",
      callback: async () => {
        const { workspace } = this.app;
        let leaves = workspace.getLeavesOfType(VIEW_TYPE_CHAT);
        if (leaves.length == 0) {
          const leaf = this.app.workspace.getRightLeaf(false);
          await (leaf == null ? void 0 : leaf.setViewState({
            type: VIEW_TYPE_CHAT,
            active: false
          }));
          leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_CHAT);
        }
        if (leaves.length != 0) {
          this.app.workspace.revealLeaf(leaves[0]);
        }
      }
    });
    this.addSettingTab(new ChatSettingTab(this.app, this));
  }
  onunload() {
  }
  async activateView() {
    const { workspace } = this.app;
    workspace.onLayoutReady(async () => {
      let leaf = null;
      const leaves = workspace.getLeavesOfType(VIEW_TYPE_CHAT);
      if (leaves.length == 0) {
        leaf = workspace.getRightLeaf(false);
        await (leaf == null ? void 0 : leaf.setViewState({
          type: VIEW_TYPE_CHAT,
          active: false
        }));
      }
    });
  }
  async loadSettings() {
    let saved = {};
    try {
      saved = await this.loadData();
    } catch (e) {
      console.log("Failed to load settings", e);
    }
    this.profiles = Object.assign({}, DEFAULT_SETTINGS, saved);
    normalizeProfiles(this.profiles);
  }
  async saveSettings() {
    await this.saveData(this.profiles);
  }
};
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {});

/* nosourcemap */